name: Daily Automated Commit

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Grants GITHUB_TOKEN write access

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 21f1000397@ds.study.iitm.ac.in
        run: |
          echo "# Daily Update $(date -u)" > STATUS.md

      - name: Commit & push
        run: |
          git config user.name github-actions[bot]
          git config user.email "21f1000397@ds.study.iitm.ac.in"
          git add STATUS.md
          git commit -m "Daily run $(date)"
          git push
